version: '3.1'

services:

  db:
    container_name: db_condsolidario
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1adf020b
      MYSQL_DATABASE: condsolidario
    volumes:
        - ./:/home/app